version: '{build}'
branches:
  only:
    - master
    - /^release/
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
build_script:
  - ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: t5Tm8IRM5Kcsd9zkLSYsCqu7482A4drNqb93Ev38P+Y4UtvKs6CeSWbRDD+pAz5O
    skip_symbols: true
    on:
      branch: /^(master|release)/
  - provider: GitHub
    auth_token:
      secure: DrLV7LYcBmi9YVEip+ZVfbpnn/7P/UHac+veTjG1vs0RPi6PuJSPmokHGhdmYGd5
    artifact: /Serilog.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: /^release/